name: clean_architecture_cli
description: A Dart CLI tool for generating clean architecture folders and updating pubspec.yaml in Flutter projects.
version: 1.0.0
homepage: https://github.com/farooq958/clean_architecture_cli
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  yaml: ^3.1.2
  yaml_edit: ^2.2.1


dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
executables:
  clean_architecture_cli: bin/clean_architecture_cli.dart
flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/gifs/
